/**
 * @fileoverview GSC Exporter for MW2 Class Editor.
 * Serializes the central Store state into a game-ready GSC script.
 */

const exporter = {
  /**
   * Generates a complete GSC script string for the current 15 classes.
   * @returns {string} The formatted GSC script.
   */
  generateGSC() {
    const state = store.getState();
    const classes = state.classes;
    let gsc = "// =====================================================\n";
    gsc += "//  MW2 Custom Class Initialization Script\n";
    gsc += "//  Generated by MW2 Class Editor\n";
    gsc += "// =====================================================\n\n";
    
    gsc += "initClasses()\n{\n";
    gsc += "    self endon(\"disconnect\");\n\n";

    classes.forEach((cls, i) => {
      gsc += `    // --- Class ${i + 1}: ${cls.name} ---\n`;
      
      // Basic Info
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"name\", \"${cls.name}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"inUse\", true);\n`;

      // Primary Weapon (weaponSetups[0])
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"weaponSetups\", 0, \"weapon\", \"${cls.primaryWeapon}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"weaponSetups\", 0, \"attachment\", 0, \"${cls.primaryAttach1}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"weaponSetups\", 0, \"attachment\", 1, \"${cls.primaryAttach2}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"weaponSetups\", 0, \"camo\", \"${cls.primaryCamo}\");\n`;

      // Secondary Weapon (weaponSetups[1])
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"weaponSetups\", 1, \"weapon\", \"${cls.secondaryWeapon}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"weaponSetups\", 1, \"attachment\", 0, \"${cls.secondaryAttach1}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"weaponSetups\", 1, \"attachment\", 1, \"${cls.secondaryAttach2}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"weaponSetups\", 1, \"camo\", \"${cls.secondaryCamo}\");\n`;

      // Equipment & Perks
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"perks\", 0, \"${cls.equipment}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"perks\", 1, \"${cls.perk1}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"perks\", 2, \"${cls.perk2}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"perks\", 3, \"${cls.perk3}\");\n`;
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"perks\", 4, \"${cls.deathstreak}\");\n`;
      
      // Special Grenade
      gsc += `    self setPlayerData(\"customClasses\", ${i}, \"specialGrenade\", \"${cls.specialGrenade}\");\n`;
      gsc += "\n";
    });

    gsc += "}\n";
    return gsc;
  }
};
